spring.main.allow-bean-definition-overriding=true
es.servers=http://localhost:9200
es.indexType=book
es.aliasName=books


# MyBatis 配置
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=cn.zealon.readingcloud.common.pojo

# 打印 SQL 日志（可选，方便调试）
logging.level.cn.zealon.readingcloud.homepage.dao=debug
logging.level.com.ibatis=debug

# MyBatis Plus SQL 日志（必加）
logging.level.com.baomidou.mybatisplus=debug
logging.level.java.sql=debug
logging.level.org.springframework.jdbc=debug
